### ISSUE TITLE
Unexplained Crash During Server Join

### ISSUE THREAD

**Issue by Lockdown00-png** [Leclowndu93150/Pretty-Rain#7]
For some reason the mod works just fine in singleplayer, yet joining a modded server it throws a very odd error saying the rain particle is null?
[crash-2024-12-24_16.42.30-client.txt](https://github.com/user-attachments/files/18242006/crash-2024-12-24_16.42.30-client.txt)

**Comment by Leclowndu93150** [comment]
oh okay, that's more context because the person that reported that before didn't say anything else. i'll take a look thanks;

**Comment by Lockdown00-png** [comment]
Of course, and apologies for the mess of a log, our server is heavily modded.

**Comment by Leclowndu93150** [comment]
does the modded server have the mod ?
here's a vanilla server and it just works
![2024-12-25_10 01 43](https://github.com/user-attachments/assets/7fb28f22-e8d3-4182-8025-99e39e924a1d)

**Comment by Leclowndu93150** [comment]
http://temp.sh/FQWKn/particlerain-1.0.4.jar
try this

**Comment by Lockdown00-png** [comment]
Apologies for the delay, also no the mod was not installed on the server originally. Tested the mod without it being installed in the server and the game crashed during rain. No difference was found with it installed serverside, but in case there is a difference I'll upload the log from both attempts. Keep in mind this is also with shaders and such in use so there could be other factors at play.
[crash-2024-12-25_11.15.33-client.txt](https://github.com/user-attachments/files/18246632/crash-2024-12-25_11.15.33-client.txt)
[crash-2024-12-25_11.11.30-client.txt](https://github.com/user-attachments/files/18246631/crash-2024-12-25_11.11.30-client.txt)

**Comment by Leclowndu93150** [comment]
thank you. it's a weird but and i'm still looking into solving it

**Comment by Lockdown00-png** [comment]
No worries, don't be shy to poke me if you need more testing.

**Comment by Leclowndu93150** [comment]
now fixed in 1.0.4

**Comment by SlimF** [comment]
Still crashing on my computer even with 1.0.4
[crash-2024-12-28_17.05.13-client.txt](https://github.com/user-attachments/files/18266550/crash-2024-12-28_17.05.13-client.txt)
[debug.log](https://github.com/user-attachments/files/18266552/debug.log)

**Comment by Leclowndu93150** [comment]
you have to add the mod to the server

**Comment by SlimF** [comment]
Ahh apologies, I thought it was a client-side mod. It is working!
